# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='rol',
            name='permiso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSeguridad.Permiso'),
            preserve_default=False,
        ),
    ]
