# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSeguridad', '0002_auto_20171120_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='aplicacion',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='rol',
            name='aplicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSeguridad.Aplicacion'),
            preserve_default=False,
        ),
    ]
