# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('programacurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.ProgramaCurricular')),
            ],
        ),
        migrations.AddField(
            model_name='contenidoprograma',
            name='programacurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.ProgramaCurricular'),
        ),
    ]
