# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUniversidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=2)),
                ('fin', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='sede',
            name='programacurricular',
        ),
        migrations.AddField(
            model_name='contenidoprograma',
            name='tiempo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='contenidoprograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.ContenidoPrograma'),
        ),
        migrations.AddField(
            model_name='horario',
            name='contenidoprograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.ContenidoPrograma'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.Hora'),
        ),
        migrations.AddField(
            model_name='horario',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.Sede'),
        ),
        migrations.AddField(
            model_name='contenidoprograma',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.Facultad'),
            preserve_default=False,
        ),
    ]
