# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUniversidad', '0002_auto_20171116_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='contenidoprograma',
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUniversidad.Materia'),
            preserve_default=False,
        ),
    ]
