from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from appUniversidad.views import (
    HomePage,
    ProgramaCurricularDetailView,
    ProgramaCurricularList,
    ProgramaCurricularCreate,
    ProgramaCurricularUpdate,
    ProgramaCurricularDelete,
    FacultadDetailView,
    FacultadList,
    FacultadCreate,
    FacultadUpdate,
    FacultadDelete,
    ContenidoProgramaDetailView,
    ContenidoProgramaList,
    ContenidoProgramaCreate,
    ContenidoProgramaUpdate,
    ContenidoProgramaDelete,
    MateriaDetailView,
    MateriaList,
    MateriaCreate,
    MateriaUpdate,
    MateriaDelete,
    HoraDetailView,
    HoraList,
    HoraCreate,
    HoraUpdate,
    HoraDelete,
    SedeDetailView,
    SedeList,
    SedeCreate,
    SedeUpdate,
    SedeDelete,
    HorarioDetailView,
    HorarioList,
    HorarioCreate,
    HorarioUpdate,
    HorarioDelete
)

urlpatterns = [
    url(r'home/$', HomePage.as_view(), name='home'),
    url(
        r'^login/$',
        LoginView.as_view(
            template_name='appUniversidad/login.html'
        ),
        name='login'
    ),
    url(
        r'^logout/$',
        LogoutView.as_view(next_page=reverse_lazy('login')),
        name='logout'
    ),
    url(
        r'^programacurricular/(?P<pk>\d+)$',
        ProgramaCurricularDetailView.as_view(),
        name='programascurricularesdetailview'
    ),
    url(
        r'programascurriculares/$',
        ProgramaCurricularList.as_view(),
        name='programascurricularesList'
    ),
    url(
        r'^crear-programacurricular$',
        ProgramaCurricularCreate.as_view(),
        name='crear-programacurricular'
    ),
    url(
        r'^programascurricularesedit/(?P<pk>\d+)$',
        ProgramaCurricularUpdate.as_view(),
        name='programascurricularesedit'
    ),
    url(
        r'^programascurricularesdelete/(?P<pk>\d+)$',
        ProgramaCurricularDelete.as_view(),
        name='programascurricularesdelete'
    ),
    url(
        r'^facultad/(?P<pk>\d+)$',
        FacultadDetailView.as_view(),
        name='facultadesdetailview'
    ),
    url(
        r'facultades/$',
        FacultadList.as_view(),
        name='facultadesList'
    ),
    url(
        r'^crear-facultad$',
        FacultadCreate.as_view(),
        name='crear-facultad'
    ),
    url(
        r'^facultadesedit/(?P<pk>\d+)$',
        FacultadUpdate.as_view(),
        name='facultadesedit'
    ),
    url(
        r'^facultadesdelete/(?P<pk>\d+)$',
        FacultadDelete.as_view(),
        name='facultadesdelete'
    ),
    url(
        r'^contenidoprograma/(?P<pk>\d+)$',
        ContenidoProgramaDetailView.as_view(),
        name='contenidosprogramasdetailview'
    ),
    url(
        r'contenidosprogramas/$',
        ContenidoProgramaList.as_view(),
        name='contenidosprogramasList'
    ),
    url(
        r'^crear-contenidoprograma$',
        ContenidoProgramaCreate.as_view(),
        name='crear-ContenidoPrograma'
    ),
    url(
        r'^contenidosprogramasedit/(?P<pk>\d+)$',
        ContenidoProgramaUpdate.as_view(),
        name='contenidosprogramasedit'
    ),
    url(
        r'^contenidosprogramasdelete/(?P<pk>\d+)$',
        ContenidoProgramaDelete.as_view(),
        name='contenidosprogramasdelete'
    ),
    url(
        r'^materia/(?P<pk>\d+)$',
        MateriaDetailView.as_view(),
        name='materiasdetailview'
    ),
    url(
        r'materias/$',
        MateriaList.as_view(),
        name='materiasList'
    ),
    url(
        r'^crear-materia$',
        MateriaCreate.as_view(),
        name='crear-materia'
    ),
    url(
        r'^materiasedit/(?P<pk>\d+)$',
        MateriaUpdate.as_view(),
        name='materiasedit'
    ),
    url(
        r'^materiasdelete/(?P<pk>\d+)$',
        MateriaDelete.as_view(),
        name='materiasdelete'
    ),
    url(
        r'^hora/(?P<pk>\d+)$',
        HoraDetailView.as_view(),
        name='horasdetailview'
    ),
    url(
        r'horas/$',
        HoraList.as_view(),
        name='horasList'
    ),
    url(
        r'^crear-hora$',
        HoraCreate.as_view(),
        name='crear-hora'
    ),
    url(
        r'^horasedit/(?P<pk>\d+)$',
        HoraUpdate.as_view(),
        name='horasedit'
    ),
    url(
        r'^horasdelete/(?P<pk>\d+)$',
        HoraDelete.as_view(),
        name='horasdelete'
    ),
    url(
        r'^sede/(?P<pk>\d+)$',
        SedeDetailView.as_view(),
        name='sedesdetailview'
    ),
    url(
        r'sedes/$',
        SedeList.as_view(),
        name='sedesList'
    ),
    url(
        r'^crear-sede$',
        SedeCreate.as_view(),
        name='crear-sede'
    ),
    url(
        r'^sedesedit/(?P<pk>\d+)$',
        SedeUpdate.as_view(),
        name='sedesedit'
    ),
    url(
        r'^sedesdelete/(?P<pk>\d+)$',
        SedeDelete.as_view(),
        name='sedesdelete'
    ),
    url(
        r'^horario/(?P<pk>\d+)$',
        HorarioDetailView.as_view(),
        name='horariosdetailview'
    ),
    url(
        r'horarios/$',
        HorarioList.as_view(),
        name='horariosList'
    ),
    url(
        r'^crear-horario$',
        HorarioCreate.as_view(),
        name='crear-horario'
    ),
    url(
        r'^horariosedit/(?P<pk>\d+)$',
        HorarioUpdate.as_view(),
        name='horariosedit'
    ),
    url(
        r'^horariosdelete/(?P<pk>\d+)$',
        HorarioDelete.as_view(),
        name='horariosdelete'
    ),
]
